### ISSUE TITLE
Rename :secure to :use_https in client initialization

### ISSUE THREAD

**Issue by kellysutton** [imgix/imgix-rb#11]
`:secure` should still be valid, but deprecated.

**Comment by paulstraw** [comment]
Since we're going to bump to `1.0.0` anyhow with the `Client#sign_path` removal, would it make sense to completely remove `:secure` in that version? That way it's a clean break. I'd like to split it into `:use_https` and `:sign_urls`.

**Comment by kellysutton** [comment]
I think `:use_https` (defaulted to `true`) makes sense.

The existence of a `:token` should act as the conditional as to whether or not sign a URL. That is, if a `:token` is not specified, URLs do not get signed. What do you think?

**Comment by paulstraw** [comment]
I can dig it, but maybe rename `:token` to `:secure_url_token` to be a bit more clear, as well as match [the copy in the app](http://paul.st/e2Of)?

**Comment by kellysutton** [comment]
Yep. Sounds good.
