### ISSUE TITLE
feat: optionally disable path encoding

### ISSUE THREAD

**Issue by luqven** [imgix/imgix-rb#117]
## Description
> Related PR: https://github.com/imgix/js-core/pull/314

Add `disablePathEncoding` functionality to the URL building logic in  in the [`to_url`](https://github.com/imgix/imgix-rb/blob/4fb9f0011a70881c047c9a18020a284963280ef9/lib/imgix/path.rb#L17-L27) and [`to_srcset`](https://github.com/imgix/imgix-rb/blob/4fb9f0011a70881c047c9a18020a284963280ef9/lib/imgix/path.rb#L46-L62) functions. This way, users can decide to opt-out of path encoding.

Probably a good way of handling this would be a new `option`, `disablePathEncoding`, in those functions.

**Comment by pypas** [comment]
Hey @luqven can I work on this one?

**Comment by sherwinski** [comment]
@pypas Yes please go for it!

**Comment by luqven** [comment]
Hey @pypas,

I wanted to quickly check in to see if you're still planning on tackling this. If you are, I'll go ahead and assign this issue to you.

In terms of next steps, please either comment here or open a RFC (request for comment) draft PR explaining the change you'd like to implement.

You can also take a look at our contributing guidelines to get you started.

If you have any trouble at all getting setup or have any questions, don't hesitate to comment here and tag a team member.

**Comment by pypas** [comment]
@luqven I am so sorry, had totally missed the reply! Will start working on it now

**Comment by luqven** [comment]
@pypas no worries at all and no rush! As I said before if you run into any blockers don't hesitate to ping a team member and we'll be happy to help.

**Comment by luqven** [comment]
Addressed by #124
