### ISSUE TITLE
chore(test): more test dependencies to a separate group in Gemfile

### ISSUE THREAD

**Issue by luqven** [imgix/imgix-rb#118]
## Descriptions
> related files: https://github.com/imgix/imgix-rb/blob/main/Gemfile

Move test dependencies to a separate group in Gemfile

**Comment by Jaskaran2** [comment]
Hi @luqven , may I pick this up?

**Comment by luqven** [comment]
Hey @Jaskaran2 👋,

Go for it! I'll marked this issue as assigned to you.

In terms of next steps, please either comment here or open a RFC (request for comment) draft PR explaining the change you'd like to implement.

You can also take a look at our contributing guidelines to get you started.

If you have any trouble at all getting setup or have any questions, don't hesitate to comment here and tag a team member.
