### ISSUE TITLE
Asset fingerprint gets URL-encoded and breaks image filenames

### ISSUE THREAD

**Issue by spaghetticode** [imgix/imgix-rb#129]
**Describe the bug**

When image path includes a timestamp fingerprint (this seems still kinda normal when working with Paperclip on a Rails application) `Imgix::Path.new.to_url` returns a non-working URL since it URL-encodes the question mark. 

I understand that removing the query and the params should be probably responsibility of the API user (in this case [imgix-rails](https://github.com/imgix/imgix-rails) gem), but I'm wondering if the `Imgix::Path` class should be more flexible and avoid encoding query params in the path, when present. Previously, as [this issue](https://github.com/imgix/imgix-rb/issues/34) shows the library didn't explicitly support fingerprints, but it didn't break them either so badly.

**To Reproduce**

```ruby
path_with_fingerprint = "some/image.jpg?123123"
Imgix::Path.new("https://example.imgix.net", nil, path_with_fingerprint).to_url
=> "https://example.imgix.net/some/image.jpg%3F123123"
```

**Expected behaviour**

Question mark is not encoded, the final URL is `https://example.imgix.net/some/image.jpg?123123`

**Information:**

- @imgix/rb version: from v4.1

**Comment by luqven** [comment]
Hey @spaghetticode thanks for taking the time to open this issue!

I can see why, when working with timestamps, this can be a problem. 

For now, maybe we can side-step this issue by setting the `to_url` functions' `options` [argument](https://github.com/imgix/imgix-rb#usage) to `{disable_path_encoding: true}`:

```ruby
path_with_fingerprint = "some/image.jpg?123123"
Imgix::Path.new("https://example.imgix.net", nil, path_with_fingerprint).to_url({}, {disable_path_encoding: true})
=> "https://example.imgix.net/some/image.jpg?123123"
```

Ideally, we'd allow developers to pass in a custom `encoder` function that would override our default encoding behavior, as we do in `@imgix/js-core`. I can't give you a time estimate as to when, but we'll discuss this and look into potentially adding that here as well.

Thanks so much again for taking the time to report this, and please let me know if this helps resolve your issue.

**Comment by luqven** [comment]
Going to go ahead and consider this resolved upstream in https://github.com/imgix/imgix-rails/issues/124
