### ISSUE TITLE
Why does it alway return a secure URL?

### ISSUE THREAD

**Issue by krzkrzkrz** [imgix/imgix-rb#14]
I am doing:

```
$imgix = Imgix::Client.new(host: %w[app-name0.imgix.net app-name1.imgix.net app-name2.imgix.net app-name3.imgix.net], token: ENV['IMGIX_KEY'], secure: false)
$imgix.path('/coming-soon.png').to_url
 => "http://app-name1.imgix.net/coming-soon.png?ixlib=rb-0.3.5&s=af314a91f11f0a3cef3397758ba01d8e"
```

And it keeps trying to sign the url? I am assuming the `s` param indicates a `secure` URL? Or am I misunderstanding?

**Comment by hellvinz** [comment]
looking at the code https://github.com/imgix/imgix-rb/blob/bf1e5966780dd111e244c168146dc15e1b2b25e4/lib/imgix/path.rb#L46
it seems that if you don't put a token in Imgix::Client.new you won't have a signature

**Comment by kellysutton** [comment]
@krzkrzkrz Sorry for the slight confusion here. The `:secure` key refers to whether or not use HTTPS. That defaults to true.

As @hellvinz pointed out, not specifying a `:token` will prevent the images from being signed.

I'm closing this for now, but feel free to reopen if you have more issues!
