### ISSUE TITLE
Expires query param?

### ISSUE THREAD

**Issue by toobulkeh** [imgix/imgix-rb#31]
Is there a recommend way to perform https://docs.imgix.com/setup/securing-images#sts=Expiring URLs using this client library?

**Comment by toobulkeh** [comment]
```ruby
client = Imgix::Client.new(...)
expiration_time = (Time.now + 20.minutes).to_i
client.path("...").expires(expiration_time)
```

appears to work well

**Comment by jayeb** [comment]
🎢 😅

**Comment by toobulkeh** [comment]
Haha -- sorry about that -- rubber ducking via github issues again 🙄 

I had some additional edits with errors that were appearing due to older versions -- and conflicting imgix-fluid issues -- mainly https://github.com/imgix/imgix.js/issues/77#issuecomment-318485336
