### ISSUE TITLE
Upgrading from 0.3.5 to 1.2.2 

### ISSUE THREAD

**Issue by veganstraightedge** [imgix/imgix-rb#40]
Hi there. 👋🏻

I'm new to a project at work that uses this gem. It has a pretty old version (`0.3.5`). I'd like to upgrade it to the latest. 

Do you know of any breaking changes between `0.3.5` and `1.2.2`?

Thanks!

**Comment by jayeb** [comment]
Hello! You can check our [Changelog](https://github.com/imgix/imgix-rb/blob/master/CHANGELOG.md) to see a list of changes version to version. Looks like you'll mostly need to deal with a couple of option renames that landed with 1.0.0.

I'm gonna close this ticket for now, but if you have any further questions I'm happy to help.

**Comment by veganstraightedge** [comment]
Thank you!
