### ISSUE TITLE
Make signature optional

### ISSUE THREAD

**Issue by jokklan** [imgix/imgix-rb#5]
It would be awesome if the signature was optional, so this gem could be used to create normal imgix url's (not signed).

**Comment by kellysutton** [comment]
Whoops. This is currently possible with the latest version of imgix-rb. Cheers!

**Comment by toobulkeh** [comment]
How is this possible? secure: false doesn't do this, and path still returns a signed URL

**Comment by toobulkeh** [comment]
To those wondering, I dug through the source and the answer is just to not provide a token when setting the client:

``` ruby
@client ||= Imgix::Client.new(host: ENV["IMGIX_SOURCE"], include_library_param: false, secure: true)
```

https://github.com/imgix/imgix-rb/blob/master/lib/imgix/client.rb#L33

**Comment by kellysutton** [comment]
Hi @toobulkeh,

Sorry about the confusion there. `:secure` refers to whether or not to use HTTPS. That can definitely be better named to something like `:use_https`.

We'll work on deprecating that for 0.4.x.

The solution you've found is the correct way to do what you were trying to do.
