### ISSUE TITLE
Introduce Rubocop

### ISSUE THREAD

**Issue by janklimo** [imgix/imgix-rb#51]
Not sure if this was discussed before (couldn't find any references) but I think the repo could benefit from using Rubocop. Establishing a clear baseline would help make future additions only modify relevant code and enforce a set of standards for the future. 

There are 512 offenses detected ([source](https://pastebin.com/Ry5dGZxY)) right now with the default set of rules. 440 of those can be autocorrected, the rest will need some work. Looking for feedback first 👍

**Comment by sherwinski** [comment]
Personally, I am for adding this. I do have one question based on the Rubocop documentation:

> RuboCop supports the following Ruby implementations:
>
> MRI 2.3+
> JRuby 9.1+

Do you foresee there being any issues using Rubocop if imgix-rb also wants to support rbx/rubinius?

**Comment by ericdeansanchez** [comment]
Since we have already introduced many rubocop changes in #65, #66, and #67 (and since we aim to `allow_failures` on rbx with #70), I am closing this issue.
